### ISSUE TITLE
[Feature Request] Missing language keys

### ISSUE THREAD

**Issue by Romz24** [CleanroomMC/InventoryBogoSorter#14]
I tried to translate the mod into my language, but I noticed that some language keys are missing from the file.

- Enable auto hotbar refill
Link: [ConfigGui.java#L92](https://github.com/CleanroomMC/InventoryBogoSorter/blob/master/src/main/java/com/cleanroommc/bogosorter/common/config/ConfigGui.java#L92)
- Auto refill damage threshold
Link: [ConfigGui.java#L104](https://github.com/CleanroomMC/InventoryBogoSorter/blob/master/src/main/java/com/cleanroommc/bogosorter/common/config/ConfigGui.java#L104)

**Comment by brachy84** [comment]
Fixed. Ill upload the fix to cf in the next few days
