### ISSUE TITLE
[Bug] Crashes on boot with IC2 Classic

### ISSUE THREAD

**Issue by Drazden** [CleanroomMC/InventoryBogoSorter#16]
Crash report: https://gist.github.com/Drazden/feaf5dd1088dbab6ca89560299618767#file-crash-2022-09-03_11-49-21-client-txt

When using BOGO sorter with IC2 Classic the game crashes instantly upon startup. I assume this is due to the regular IC integrations and the mods sharing the same jar file.  IC2 Classic boots fine with ModularUI and MixinBooter installed.

**Comment by brachy84** [comment]
fixed in 1.0.10
