### ISSUE TITLE
[1.12.2] Crash Upon Opening Sort Config

### ISSUE THREAD

**Issue by SaltSouls** [CleanroomMC/InventoryBogoSorter#2]
The game crashes the instant I try to open the mods config menu.
Minecraft: 1.12.2
Forge: 14.23.5.2860
Inventory Bogo Sorter: 1.0.3
ModularUI: 1.0.2
Crash Report: https://pastes.dev/gTHst3tEqz

Side note: Translation key for the key binds was not set, so they look really strange.
![image](https://user-images.githubusercontent.com/36361103/177014443-affa4bd0-bc0f-44a9-8769-c490db59499f.png)

**Comment by brachy84** [comment]
I uploaded new version of ModularUI (1.0.3) that should fix it
