### ISSUE TITLE
[Bug]Clearing botania flower pouch when sorting in the gui of it

### ISSUE THREAD

**Issue by mczph** [CleanroomMC/InventoryBogoSorter#22]
Just open a flower pouch,put some flowers in it.And then sort with InventoryBogoSorter,the flowers will be cleared.

**Comment by brachy84** [comment]
Does it still happen? it should be fixed

**Comment by Krutoy242** [comment]
Just tested on `bogosorter-1.1.2` - no issue, Flower Pouch kept its content after sorting.
