### ISSUE TITLE
[Suggstion] Why is the number of items not in reverse order?

### ISSUE THREAD

**Issue by IAmNotGEM** [CleanroomMC/InventoryBogoSorter#24]
thank you

**Comment by brachy84** [comment]
What do you mean exactly?

**Comment by IAmNotGEM** [comment]
> What do you mean exactly?

When organizing the inventory, the large number of items in front

**Comment by brachy84** [comment]
Ah that. I wanted to make it configurable for each rule.

**Comment by IAmNotGEM** [comment]
> Ah that. I wanted to make it configurable for each rule.

okay, thanks
