### ISSUE TITLE
Mod Support request

### ISSUE THREAD

**Issue by penturt** [CleanroomMC/InventoryBogoSorter#31]
Could you please add support for the following mods:

[Expanded Storage](https://www.curseforge.com/minecraft/mc-mods/expanded-storage) 
[Dank Storage](https://www.curseforge.com/minecraft/mc-mods/dank-storage)
[Sophisticated Backpacks](https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks)

Been following and have tried out the mod, really like it, but these are 3 major mod that would be nice to have support for. The only other inventory sorting mod out there lets you sort in these mods, but if any of the stacks are over 64 items it causes mayhem.

**Comment by juraj-hrivnak** [comment]
[Expanded Storage](https://www.curseforge.com/minecraft/mc-mods/expanded-storage) and [Sophisticated Backpacks](https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks) are both not for 1.12.2
