### ISSUE TITLE
【BUG】Error reported when using catserver to open a service

### ISSUE THREAD

**Issue by Lonelyxiya** [CleanroomMC/InventoryBogoSorter#32]
please fix this asap or my Modpack will not work.
log links: [latest(4).log](https://github.com/CleanroomMC/InventoryBogoSorter/files/10199127/latest.4.log)
I found this last night troubleshooting mod issues on the Modpack server. What a waste of my time and effort :(

**Comment by Lonelyxiya** [comment]
I deleted the mod and the server side worked fine

**Comment by brachy84** [comment]
What is catserver? And that log doesnt tell anything about a crash or error related to this mod

**Comment by Lonelyxiya** [comment]
url: https://catmc.org/ 
I deleted the bogosorter and it works fine

**Comment by Lonelyxiya** [comment]
But installing the bogosorter server does not work.

**Comment by Xikaro** [comment]
I previously tested on many server core, the mod only works on forge

**Comment by Lonelyxiya** [comment]
> Does that mean bogosorter is not compatible with other server cores?

**Comment by Lonelyxiya** [comment]
#https://github.com/Luohuayu/CatServer/issues/704

**Comment by Lonelyxiya** [comment]
You can fix the ASM/mixin issue with CatServer and bogosorter

**Comment by brachy84** [comment]
No I can't. That log doesn't contain any information about any incompatibility and therefore can not find the cause.
