### ISSUE TITLE
[bug] Bogosort does not check if the gregtech version is CEU or CE

### ISSUE THREAD

**Issue by BraggestSage833** [CleanroomMC/InventoryBogoSorter#36]
Crash on world load with no class GTTool found. This class is only in GTCEu as a part of the tools reworks. This crash does not affect newly generated worlds. 

[crash report](https://pastebin.com/ZAGJxdYu)

Edit: me not remembering how URLs work in git

**Comment by brachy84** [comment]
Compat with GTCEu and GTCE at the same time isnt really possible. (Maybe it can be done, but i dont really want to do that.)

**Comment by brachy84** [comment]
Should be fixed

**Comment by ferreiraalex** [comment]
not fixed

**Comment by brachy84** [comment]
wdym

**Comment by ferreiraalex** [comment]
I have gtce and if open config  bogo sorter have crash

**Comment by brachy84** [comment]
give crash log

**Comment by ferreiraalex** [comment]
[crash-2023-08-10_03.59.50-server.txt](https://github.com/CleanroomMC/InventoryBogoSorter/files/12309086/crash-2023-08-10_03.59.50-server.txt)
