### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by IAmNotGEM** [CleanroomMC/InventoryBogoSorter#42]
[15:11:30] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_341]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_341]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_341]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_341]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_341]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_341]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_341]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_341]
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:62) [CatServer-fed56812-universal.jar:git-CatServer-1.12.2-fed56812]
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:31) [CatServer-fed56812-universal.jar:git-CatServer-1.12.2-fed56812]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_341]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_341]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_341]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_341]
	at catserver.server.CatServerLaunch.main(CatServerLaunch.java:17) [CatServer-fed56812-universal.jar:git-CatServer-1.12.2-fed56812]
Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    net/minecraft/entity/player/EntityPlayer.func_71059_n(Lnet/minecraft/entity/Entity;)V @1282: invokestatic
  Reason:
    Type 'net/minecraft/entity/Entity' (current frame, stack[1]) is not assignable to 'net/minecraft/item/ItemStack'
  Current Frame:
    bci: @1282
    flags: { }
    locals: { 'net/minecraft/entity/player/EntityPlayer', 'net/minecraft/entity/Entity', float, float, float, integer, integer, integer, integer, 'net/minecraftforge/event/entity/player/CriticalHitEvent', integer, double, double_2nd, float, integer, integer, top, double, double_2nd, double, double_2nd, double, double_2nd, integer, 'net/minecraft/item/ItemStack', 'net/minecraft/entity/Entity', 'net/minecraft/item/ItemStack' }
    stack: { 'net/minecraft/entity/player/EntityPlayer', 'net/minecraft/entity/Entity', 'net/minecraft/util/EnumHand' }
  Bytecode:
    0x0000000: 2a2b b807 4c9a 0004 b12b b607 4f99 05f7
    0x0000010: 2b2a b607 529a 05ef 2ab2 0163 b601 75b9
    0x0000020: 031a 0100 9045 2bc1 0004 9900 152a b602
    0x0000030: 252b c000 04b6 0756 b807 5a46 a700 0e2a
    0x0000040: b602 25b2 0760 b807 5a46 2a13 0368 b607
    0x0000050: 6338 0424 1302 5817 0417 046a 1303 3b6a
    0x0000060: 626a 4525 1704 6a46 2ab6 022f 240b 959d
    0x0000070: 0009 250b 959e 058f 1704 1307 6495 9e00
    0x0000080: 0704 a700 0403 3605 0336 0603 3607 1507
    0x0000090: 2ab8 0767 6036 072a b603 1499 002e 1505
    0x00000a0: 9900 292a b401 c901 c000 022a b402 0a2a
    0x00000b0: b402 1a2a b402 17b2 076a 2ab6 0295 0c0c
    0x00000c0: b602 9984 0701 0436 0615 0599 003d 2ab4
    0x00000d0: 0367 0b95 9e00 342a b401 bf9a 002d 2ab6
    0x00000e0: 076d 9a00 262a b603 6b9a 001f 2ab2 0770
    0x00000f0: b605 009a 0015 2ab6 02ab 9a00 0e2b c100
    0x0000100: 0499 0007 04a7 0004 0336 0815 0899 000e
    0x0000110: 2ab6 0314 9a00 0704 a700 0403 3608 2a2b
    0x0000120: 1508 1508 9900 0913 0771 a700 040c b807
    0x0000130: 753a 0919 09c6 0007 04a7 0004 0336 0815
    0x0000140: 0899 000b 2419 09b6 077a 6a45 2425 6245
    0x0000150: 0336 0a2a b407 7d2a b407 8066 8d39 0b15
    0x0000160: 0599 0036 1508 9a00 3115 069a 002c 2ab4
    0x0000170: 01bf 9900 2518 0b2a b607 838d 989c 001a
    0x0000180: 2ab2 06bd b607 223a 0d19 0db6 0434 c107
    0x0000190: 8599 0006 0436 0a0b 380d 0336 0e2a b807
    0x00001a0: 8836 0f2b c100 0499 004c 2bc0 0004 b607
    0x00001b0: 8938 0d15 0f9e 003e 2bb6 078a 9a00 37bb
    0x00001c0: 078c 592a b604 7a2b b907 8f01 0004 b707
    0x00001d0: 923a 10b8 0795 1910 b904 9602 0019 10b6
    0x00001e0: 0796 9a00 1104 360e 2b19 10b6 0799 b907
    0x00001f0: 9c02 002b b407 9d39 112b b407 9e39 132b
    0x0000200: b407 9f39 152b 2ab8 07a3 24b6 07a4 3617
    0x0000210: 1517 9903 b615 079e 0082 2bc1 0004 9900
    0x0000220: 2e2b c000 042a 1507 8613 0368 6a2a b402
    0x0000230: b513 03f0 6ab8 03f7 8d2a b402 b513 03f0
    0x0000240: 6ab8 03f4 768d b607 a8a7 0033 2b2a b402
    0x0000250: b513 03f0 6ab8 03f7 7615 0786 6a13 0368
    0x0000260: 6a8d 1407 a92a b402 b513 03f0 6ab8 03f4
    0x0000270: 1507 866a 1303 686a 8db6 07ad 2a59 b403
    0x0000280: 2114 07ae 6bb5 0321 2a59 b403 2414 07ae
    0x0000290: 6bb5 0324 2a03 b607 b215 0a99 00bb 0c2a
    0x00002a0: b807 b624 6a62 3818 2ab4 01c9 1204 2bb6
    0x00002b0: 0341 0f14 0250 0fb6 0349 b607 bab9 07bb
    0x00002c0: 0100 3a19 1919 b906 0601 0099 0067 1919
    0x00002d0: b906 0a01 00c0 0004 3a1a 191a 2aa5 0052
    0x00002e0: 191a 2ba5 004c 2a19 1ab6 07be 9a00 432a
    0x00002f0: 191a b607 c214 07c3 989c 0036 191a 2ab8
    0x0000300: 07a3 b607 c817 18b6 0657 9900 2519 1a2a
    0x0000310: 1303 372a b402 b513 03f0 6ab8 03f7 8d2a
    0x0000320: b402 b513 03f0 6ab8 03f4 768d b607 a8a7
    0x0000330: ff95 2ab4 01c9 01c0 0002 2ab4 020a 2ab4
    0x0000340: 021a 2ab4 0217 b207 cb2a b602 950c 0cb6
    0x0000350: 0299 2ab6 07ce 2bc1 001b 9900 9d2b b407
    0x0000360: d199 0096 0336 182b b607 d2c0 047c 3a19
    0x0000370: bb07 d459 1811 1813 1815 b707 d63a 1abb
    0x0000380: 07d8 5919 1919 1ab6 07dc b707 df3a 1b2a
    0x0000390: b401 c9b6 0482 b604 9019 1bb9 0496 0200
    0x00003a0: 191b b607 e099 0009 0436 18a7 001c 191a
    0x00003b0: 191b b607 e3b6 07e4 9a00 0f19 1919 1bb6
    0x00003c0: 07e3 b907 e802 0015 189a 002e 2bc0 001b
    0x00003d0: b907 ec01 00bb 07ee 592b b707 efb6 07f5
    0x00003e0: 2b03 b507 d12b 1811 b507 9d2b 1813 b507
    0x00003f0: 9e2b 1815 b507 9f15 0899 0028 2ab4 01c9
    0x0000400: 01c0 0002 2ab4 020a 2ab4 021a 2ab4 0217
    0x0000410: b207 f82a b602 950c 0cb6 0299 2a2b b607
    0x0000420: fb15 089a 0050 150a 9a00 4b15 0599 0026
    0x0000430: 2ab4 01c9 01c0 0002 2ab4 020a 2ab4 021a
    0x0000440: 2ab4 0217 b207 fe2a b602 950c 0cb6 0299
    0x0000450: a700 232a b401 c901 c000 022a b402 0a2a
    0x0000460: b402 1a2a b402 17b2 0801 2ab6 0295 0c0c
    0x0000470: b602 9925 0b95 9e00 082a 2bb6 0804 2a2b
    0x0000480: b608 072b c100 0499 000b 2bc0 0004 2ab8
    0x0000490: 080b 2a2b b808 0e2a b602 253a 182b 3a19
    0x00004a0: 2bc1 0810 9900 1b2b c008 10b4 0814 3a1a
    0x00004b0: 191a c100 0499 000a 191a c000 043a 1919
    0x00004c0: 18b6 0232 9a00 4119 19c1 0004 9900 3919
    0x00004d0: 18b6 0235 3a1a 1918 1919 c000 042a b608
    0x00004e0: 1819 18b6 0232 9900 1f2a 191a b206 bdb8
    0x00004f0: 06b7 2ab2 06bd b200 d8b6 073c 2a19 19b2
    0x0000500: 06bd b807 312b c100 0499 00a7 170d 2bc0
    0x0000510: 0004 b607 8966 381a 2ab2 081b 171a 1308
    0x0000520: 1c6a b808 1fb6 04c9 150f 9e00 39bb 078c
    0x0000530: 592a b604 7a19 19b9 078f 0100 150f 0768
    0x0000540: b707 923a 1bb8 0795 191b b904 9602 0019
    0x0000550: 1bb6 0796 9a00 0f19 1919 1bb6 0799 b907
    0x0000560: 9c02 002a b401 c9c1 0821 9900 4617 1a0d
    0x0000570: 959e 003f 171a 8d14 012b 6b8e 361b 2ab4
    0x0000580: 01c9 c008 21b2 0827 2bb4 0828 2bb4 0829
    0x0000590: 2bb4 082a 1303 686a 8d63 2bb4 082b 151b
    0x00005a0: 1407 a90e 1407 a914 082c 03bc 0ab6 0831
    0x00005b0: 2a13 06e1 b606 e72a 2ab4 01c9 b408 35b4
    0x00005c0: 083a b606 e7a7 003f 2ab4 01c9 01c0 0002
    0x00005d0: 2ab4 020a 2ab4 021a 2ab4 0217 b208 3d2a
    0x00005e0: b602 950c 0cb6 0299 150e 9900 072b b608
    0x00005f0: 3e2a c100 1b99 000f 2ac0 001b b906 6f01
    0x0000600: 00b6 0841 b1                           
  Stackmap Table:
    same_frame(@9)
    append_frame(@63,Float)
    append_frame(@74,Float)
    append_frame(@120,Float)
    same_frame(@133)
    same_locals_1_stack_item_frame(@134,Integer)
    append_frame(@201,Integer,Integer,Integer)
    same_frame(@264)
    same_locals_1_stack_item_frame(@265,Integer)
    append_frame(@283,Integer)
    same_locals_1_stack_item_frame(@284,Integer)
    full_frame(@301,{Object[#2],Object[#829],Float,Float,Float,Integer,Integer,Integer,Integer},{Object[#2],Object[#829],Integer})
    full_frame(@302,{Object[#2],Object[#829],Float,Float,Float,Integer,Integer,Integer,Integer},{Object[#2],Object[#829],Integer,Float})
    append_frame(@316,Object[#1911])
    same_locals_1_stack_item_frame(@317,Integer)
    same_frame(@332)
    append_frame(@407,Integer,Double)
    append_frame(@499,Float,Integer,Integer)
    full_frame(@588,{Object[#2],Object[#829],Float,Float,Float,Integer,Integer,Integer,Integer,Object[#1911],Integer,Double,Float,Integer,Integer,Top,Double,Double,Double,Integer},{})
    same_frame(@636)
    same_frame(@665)
    append_frame(@708,Float,Object[#1539])
    same_frame_extended(@815)
    chop_frame(@818,1)
    chop_frame(@854,1)
    full_frame(@942,{Object[#2],Object[#829],Float,Float,Float,Integer,Integer,Integer,Integer,Object[#1911],Integer,Double,Float,Integer,Integer,Top,Double,Double,Double,Integer,Integer,Object[#1148],Object[#2004],Object[#2008]},{})
    same_frame(@967)
    full_frame(@1015,{Object[#2],Object[#829],Float,Float,Float,Integer,Integer,Integer,Integer,Object[#1911],Integer,Double,Float,Integer,Integer,Top,Double,Double,Double,Integer},{})
    same_frame(@1057)
    same_frame(@1107)
    same_frame(@1139)
    same_frame(@1150)
    same_frame(@1170)
    append_frame(@1215,Object[#213],Object[#829])
    same_frame_extended(@1285)
    append_frame(@1379,Float)
    chop_frame(@1456,1)
    chop_frame(@1480,2)
    same_frame(@1521)
    full_frame(@1540,{Object[#2],Object[#829]},{})

	at net.minecraft.util.datafix.DataFixesManager.func_188279_a(DataFixesManager.java:170) ~[rz.class:?]
	at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1716) ~[MinecraftServer.class:?]
	... 17 more

**Comment by brachy84** [comment]
Finally a usefull log related to #32.
Closing due to dupe issue

**Comment by IAmNotGEM** [comment]
> Finally a usefull log related to #32. Closing due to dupe issue

The server can not be loaded inside the mod, you as the author you check ah, can not open the service of the log here ah, you need more detailed logs to entertain?

**Comment by IAmNotGEM** [comment]
> Finally a usefull log related to #32. Closing due to dupe issue



> 

no more log please

**Comment by IAmNotGEM** [comment]
PIMVisitor.class is use for what? Why doesn't the server load it? @brachy84

**Comment by IAmNotGEM** [comment]
> 

Not only does the catserver have this problem, but the original forge server can't load the mod either

**Comment by IAmNotGEM** [comment]
> > 
> 
> Not only does the catserver have this problem, but the original forge server can't load the mod either

Have you tested it? @ @brachy84

**Comment by brachy84** [comment]
I tested it in a dev environment and it worked fine. Its the first time hearing this.

**Comment by IAmNotGEM** [comment]
> I tested it in a dev environment and it worked fine. Its the first time hearing this.

Okay,  forge server can load the PIMVisitor.class, but catserver can't.

> I tested it in a dev environment and it worked fine. Its the first time hearing this.

Okay,  forge server can load the PIMVisitor.class, but catserver can't.

**Comment by IAmNotGEM** [comment]
> I tested it in a dev environment and it worked fine. Its the first time hearing this.

https://github.com/Luohuayu/CatServer/blob/1.12.2/patches/net/minecraft/server/management/PlayerInteractionManager.java.patch
