### ISSUE TITLE
Crash on sorting when Advanced Connector from XNet is present in inventory

### ISSUE THREAD

**Issue by ChromaPIE** [CleanroomMC/InventoryBogoSorter#54]
Title explains.

Did more tests with Network Cable and Controller, not crashing.

Crash report: https://mclo.gs/fd86dpQ

**Comment by brachy84** [comment]
Big bruh. Are you sorting by display name or color? Disabling both should "fix" it.

**Comment by ChromaPIE** [comment]
Yea it fixes the crash

**Comment by brachy84** [comment]
should be fixed
