### ISSUE TITLE
[Dupe] Ctrl+Shift+Click output slot

### ISSUE THREAD

**Issue by Krutoy242** [CleanroomMC/InventoryBogoSorter#57]
How to reproduce:
- Install `Bogosort` + `Tconstruct`
- Craft something
- Ctrl+Shift+Click result for infinite items

https://github.com/CleanroomMC/InventoryBogoSorter/assets/936618/8c1760d7-289e-4e23-bf4b-8b00e38bfaec

[debug.log](https://github.com/CleanroomMC/InventoryBogoSorter/files/12843429/debug.log)

**Comment by brachy84** [comment]
Also works vanilla crafting table and only ctrl + lmb
