### ISSUE TITLE
Inconsistent `auto hotbar refill`

### ISSUE THREAD

**Issue by Krutoy242** [CleanroomMC/InventoryBogoSorter#58]
1. I have several Mekanism's boxes packed with blocks.
2. In first video you can see first glitch - blocks refill main hand for a split second but then stay on same slot
3. On the second video you can see, that simply rearranging boxes in inventory by shift+clicking fixing refill feature, but not for long - after several blocks placed, they stop refilling again

https://github.com/CleanroomMC/InventoryBogoSorter/assets/936618/3fbcdce8-d34a-4fea-87dd-ce82a28e9186

https://github.com/CleanroomMC/InventoryBogoSorter/assets/936618/69139eef-5f46-4201-8107-522dc5366b8c

**Comment by brachy84** [comment]
I can not reproduce

**Comment by Krutoy242** [comment]
I'm playing on server of it's important.

**Comment by brachy84** [comment]
Also can't reproduce on server. Might be a incompatibiliy with a mod in your pack

**Comment by Krutoy242** [comment]
I could try to find the mod then.

**Comment by Krutoy242** [comment]
It feels like this config option is actually fix this issue https://github.com/Krutoy242/Enigmatica2Expert-Extended/commit/de834ed7a5769b8447bb4bdf6175ee771746c5fb

It took me 5 months to find what exact option was caused problem 😅
It would greatly help other modpack devs if BogoSort would have compatibility with Quark or at least point somewhere that this option should be disabled if Quark used.
