### ISSUE TITLE
Visual glitch: Alt+Click causing item to pick up in hand

### ISSUE THREAD

**Issue by Krutoy242** [CleanroomMC/InventoryBogoSorter#59]
- Alt+LMB causing item to "grab" for a split second instead of throw into inventory.
- This glitch is inconsistent and happens not 100% of time

On the video you could see how Alt+LMB clicking bees but sometimes clicked stack "grabbed" by mouse.

(Second video is slow-mo key part of first video)

https://github.com/CleanroomMC/InventoryBogoSorter/assets/936618/dfba5ef4-9606-4004-be65-a50d79b7bf3d

https://github.com/CleanroomMC/InventoryBogoSorter/assets/936618/082a4430-2355-4db5-825d-95d5a6b1b715

**Comment by brachy84** [comment]
Is this really bothering you? It works so i think its fine

**Comment by Krutoy242** [comment]
Yes, its bothering since it looks like a malfunction / bug.
