### ISSUE TITLE
Add an option to disable the annoying "Get Bogo'd"

### ISSUE THREAD

**Issue by MatthiasMann** [CleanroomMC/InventoryBogoSorter#62]
This is the only thing which I don't like about this mod - it is annoying and provides no benefit at all.

I would like to have a config option to disable this (or adjust it's chance down to 0).

I'm using bogosorter-1.4.4 for 1.12.2

**Comment by brachy84** [comment]
Boring

**Comment by Nrmot** [comment]
How about you code an addon mod for bogoscript if you want that "disable ' get bogo'd ' " feature because it was clear that the devs for this mod will not remove that feature :trollface:
