### ISSUE TITLE
[Feature Request] Make inventory sort and sort config buttons toggable

### ISSUE THREAD

**Issue by geradeaus007** [CleanroomMC/InventoryBogoSorter#63]
I have a texture pack which makes weverything darker and the buttons in the inventory really annoy me.

![image](https://github.com/CleanroomMC/InventoryBogoSorter/assets/97235064/c36d9e5a-2951-44a1-af5b-13f2ab3c08aa)

There are two possible solutions I have come up with.
1. Make the buttons skinnable, as I have not found a way to change their design.
2. Make them toggable in the config. One for the inventory and one for containers would be best overall but one for both would be enough for me.

The second option would make it more user friendly as there are keybinds so the buttons are not nececairly needed, it would be more configurable and in my case it is easier to do than skinning the buttons.

**Comment by brachy84** [comment]
I dont see a benefit in being able to toggle them. I will add a seperate texture for the background and a config for the color.
