### ISSUE TITLE
"count" sort rule ignores total item count in inventory

### ISSUE THREAD

**Issue by wired-maya** [CleanroomMC/InventoryBogoSorter#67]
Hello,

The existing count rule only sorts stacks individually instead of taking the total of that item in the inventory into account. Is this a bug? Or, if this is the intended behaviour, would it be possible to add a proper "count" sort rule?

Thank you.

**Comment by brachy84** [comment]
fixed

**Comment by wired-maya** [comment]
thank you so much! :D
