### ISSUE TITLE
[Feature Request] Inventory Tweaks features

### ISSUE THREAD

**Issue by Krutoy242** [CleanroomMC/InventoryBogoSorter#7]
For an easier transition from IT, please add these features.

- [x] Sorting config button (in addition to keybind)
  > In IT its square with [...]
- [x] Ctrl+Leftclick to move over a single item at a time
- [x] Ctrl+Rightclick to move over a single item into a new stack at a time
- [x] `LMB+Space` to move the entire inventory over.
  > Working both directions. When from chest, hotbar not filling
- [x] ~`Shift+Doubleclick` or `CTRL+SHIFT`~ `LMB+ALT` to move every stack of a particular item
- [x] Add configurable sound on sort
- [x] `Ctrl`+`Space` in hotbar to move whole hotbar (now only works with main inventory, not hotbar)

**Comment by brachy84** [comment]
Thank you very much. I will go through them this week

**Comment by brachy84** [comment]
I add some features

- [ ] Ctrk+Shift+Q throws all items from the inventory that are the same as the hovered item
- [ ] Space+Q throws the whole inventory

**Comment by ProTriforcer** [comment]
- [ ] Sorting the player's inventory refills stacks in the hotbar

**Comment by Krutoy242** [comment]
- [ ] `Ctrl`+`Space` in hotbar to move whole hotbar (now only works with main inventory, not hotbar)

**Comment by brachy84** [comment]
> * [ ]  `Ctrl`+`Space` in hotbar to move whole hotbar (now only works with main inventory, not hotbar)

I made player hotbar sortable as its own slot group. You can use the usual key combos while hovering a hotbar slot.

**Comment by Krutoy242** [comment]
Sounds good, thank you!

**Comment by brachy84** [comment]
Isnt that a vanilla feature?

**Comment by Krutoy242** [comment]
I didn't checked yet, but it stop working when i updated IT->Bogo. I will check it again.

**Comment by Krutoy242** [comment]
Ok, sorry for missreport - it start to work again.

**Comment by Krutoy242** [comment]
I think like everything was fulfilled and i can close the issue.
