### ISSUE TITLE
Block hotkey on certain GUIs

### ISSUE THREAD

**Issue by ChromaPIE** [CleanroomMC/InventoryBogoSorter#80]
I'm talking about the Interface Terminal.

Steps to reproduce:
Open the terminal
Focus on the input box
Try to enter K or whatever the key for Bogo's config GUI is bound to
It opens the config GUI

**Comment by brachy84** [comment]
Thats the other mods fault for not focusing their fucking gui screen.

**Comment by IntegerLimit** [comment]
You could implement this feature, so it can be fixed without having to try to fix old mods (if this issue exists on other searchable GUIs). Similar to the ASM Groovy SideOnly config.

**Comment by brachy84** [comment]
Its not that simple
